//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictureServiceWebRole
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Picture", Namespace="http://schemas.datacontract.org/2004/07/PictureServiceWebRole")]
    public partial class Picture : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NameField;
        
        private byte[] PictureStreamField;
        
        private string[] TagsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] PictureStream
        {
            get
            {
                return this.PictureStreamField;
            }
            set
            {
                this.PictureStreamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Tags
        {
            get
            {
                return this.TagsField;
            }
            set
            {
                this.TagsField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IPictureService")]
public interface IPictureService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPictureService/GetPicture", ReplyAction="http://tempuri.org/IPictureService/GetPictureResponse")]
    PictureServiceWebRole.Picture GetPicture(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPictureService/UploadPicture", ReplyAction="http://tempuri.org/IPictureService/UploadPictureResponse")]
    void UploadPicture(PictureServiceWebRole.Picture picture);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IPictureServiceChannel : IPictureService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class PictureServiceClient : System.ServiceModel.ClientBase<IPictureService>, IPictureService
{
    
    public PictureServiceClient()
    {
    }
    
    public PictureServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public PictureServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PictureServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PictureServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public PictureServiceWebRole.Picture GetPicture(string name)
    {
        return base.Channel.GetPicture(name);
    }
    
    public void UploadPicture(PictureServiceWebRole.Picture picture)
    {
        base.Channel.UploadPicture(picture);
    }
}
